// get full list of expenses
GET http://localhost:5001/api/expenses

// get a list of total sum
###
GET http://localhost:5001/api/expenses/expenses/totalsum

// get expense by ID
###
GET http://localhost:5001/api/expenses/2

// filter by category type
###
GET http://localhost:5001/api/expenses/category/other
###
GET http://localhost:5001/api/expenses/category/shop
###
GET http://localhost:5001/api/expenses/category/food

// filter by month
###
GET http://localhost:5001/api/expenses/month/2

// get by amount less than 10
###
GET http://localhost:5001/api/expenses/lt10/10

// get by amount greater than 10
###
GET http://localhost:5001/api/expenses/gt10/10

// get by shop name
###
GET http://localhost:5001/api/expenses/shop/Prisma